version: "3.9"
services:
  web:
    build: .
    ports: 
      - "3000:3000"
    volumes:
      - ".:/app"
      # it is not updating
  ngrok:
    image: shkoliar/ngrok:latest
    ports:
      - 4551:4551
    links: 
      - web
    environment:
      - DOMAIN=web
      - PORT=3000
